### ISSUE TITLE
initial setting

### ISSUE THREAD

**Issue by marugy** [Lets-Travel-Well/are-you-alone-backend#1]
### 🗄️ 종류

issue 종류를 선택하세요
- Setup
## 🔍Description
> 초기세팅

## 📝Todo

- [x] 설정파일 분리
- [ ] response 형식 지정
- [x] 필요 의존성 추가
- [x] 패키지 구조 설정
