### ISSUE TITLE
refactor : code 리팩토링

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#19]
### 🗄️ 종류

issue 종류를 선택하세요

- [ ] Code Review
- [ ] New Feature
- [ ] Remove Feature
- [x] Change Logic
- [ ] Bug Fix
- [ ] Setup
## 🔍Description

> 코드 리팩토링

## 📝Todo

- [x] 임시 member 도메인
- [x] board 도메인에 cqrs패턴 적용
- [x] 서비스 단 분리 
- [x] test 도메인 삭제
- [x] 요구사항 명세 추가
