### ISSUE TITLE
refactor : people domain member로 수정

### ISSUE THREAD

**Issue by marugy** [Lets-Travel-Well/are-you-alone-backend#35]
### 🗄️ 종류

issue 종류를 선택하세요
- [x] Change Logic

## 🔍Description

> people 도메인 member로 변환

## 📝Todo
- [x] people -> member 변환하기
- [x] board Domain 안에 member 객체 반영
- [x] post id mapping 변환
- [ ] 초기 init 값 변경
