### ISSUE TITLE
setup : 초기 데이터 생성

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#43]
### 🗄️ 종류

issue 종류를 선택하세요

- [ ] Code Review
- [ ] New Feature
- [ ] Remove Feature
- [ ] Change Logic
- [ ] Bug Fix
- [x] Setup
## 🔍Description

> 초기 데이터 생성

## 📝Todo

- [x] Member 초기 데이터
- [x] 게시글 초기 데이터
- [x] 코멘트 초기 데이터
- [ ] 게시글 좋아요 초기 데이터
- [ ] 여행 좋아요 초기 데이터
