### ISSUE TITLE
feat : 마이 페이지 구현

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#49]
### 🗄️ 종류

issue 종류를 선택하세요

- [ ] Code Review
- [x] New Feature
- [ ] Remove Feature
- [ ] Change Logic
- [ ] Bug Fix
- [ ] Setup
## 🔍Description

> 마이 페이지 구현

## 📝Todo
- [ ] Journey Entity 수정
- [ ] 마이 페이지 구현
- [ ] 마이 페이지 - 내 여행 리스트 보기(내가 leader)
- [ ] 마이 페이지 - 내 여행 여행 완료
- [ ] 마이 페이지 - 완료된 여행에 대해서 후기 작성하기
- [ ] 마이 페이지 - 승인 신청한 여행
- [ ] 마이 페이지 - 지난 여행
