### ISSUE TITLE
refactor : test 도메인 삭제 및 chat 도메인 수정 더미 데이터 변경

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#51]
### 🗄️ 종류

issue 종류를 선택하세요

- [ ] Code Review
- [ ] New Feature
- [ ] Remove Feature
- [x] Change Logic
- [ ] Bug Fix
- [ ] Setup
## 🔍Description

> test 도메인 삭제 및 chat 도메인 수정

## 📝Todo

- [x] test 도메인 삭제
- [x] chat 도메인 수정
- [x] 핫플레이스 더미 데이터 수정
