### ISSUE TITLE
feat : Github action으로 CI/CD 구축

### ISSUE THREAD

**Issue by marugy** [Lets-Travel-Well/are-you-alone-backend#62]
## 🔍Description

> Github actions으로 CI/CD 구축

## 📝Todo

- [ ] Back-end CI/CD 구축
- [ ] Pull request 시 자동 테스트 진행
- [ ] 자정마다 공공데이터 DB
