### ISSUE TITLE
build : config 파일 서버로 분리 및 CI/CD 구축

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#67]
## 🔍Description

> config 서버에서 설정 정보 pull하도록 코드 수정

## 📝Todo

- [ ] config 서버에서 설정 정보 pull하도록 코드 수정
- [ ] local 환경 분리
- [ ] dev 환경 분리
- [ ] 도커 파일 작성
- [ ] CI/CD 구축
