### ISSUE TITLE
feat : 관심있는 관광지 조회 기능 추가 및 hotPlace 리팩토링

### ISSUE THREAD

**Issue by byh9811** [Lets-Travel-Well/are-you-alone-backend#79]
## 🔍Description

> 관심있는 관광지 조회 기능 추가

## 📝Todo

- [ ] Controller에 api 추가
- [ ] Service와 Repository에 관심 관광지 조회 로직 추가
- [ ] hotPlace 관련 전체적인 리팩토링
