### ISSUE TITLE
feat : 동행 신청 및 수락, 거절 API

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#81]
## 🔍Description

> 동행 신청 및 수락, 거절 API

## 📝Todo

- [x] 동행 신청 API
- [x] 동행 승락 API
- [x] 동행 거절 API
- [x] 내가 리더인 동행 조회
- [x] 참가 신청한 동행 / 참가 확정된 동행 / 참가 거절된 동행 / 다녀온 동행 (4개 상태) 조회
- [x] 내가 리더인 여행 상세 조회
