### ISSUE TITLE
feat : 동행 갔다온 사람에 대한 평점 구현

### ISSUE THREAD

**Issue by doolysmile** [Lets-Travel-Well/are-you-alone-backend#85]
## 🔍Description

> 동행 갔다온 사람에 대한 평점 구현

## 📝Todo

- [ ] 테이블 생성
- [ ] 여행이 완료 되었다는 API 구현
- [ ] 평점 API 구현
- [ ] 평점을 정규 분포로 변환하는 알고리즘 구현
